### ISSUE TITLE
About Us Page Content

### ISSUE THREAD

**Issue by hartman313** [mrengy/recycleabike#127]
https://www.devsite.recycleabike.org/about-us/ 

We need to replace the image of Chelsea with something else since she is no longer an employee of RAB and has been asked to be removed from the existing site altogether. 

Recommend this for now (and not just because it's me, haha)

![IMG_0004](https://user-images.githubusercontent.com/10117579/103373972-55d44a00-4aa4-11eb-834d-baba1fca661d.jpg)

___________________________________________________________

<h2>Our Community Bike Shop</h2>

<p>Our community bike shop in Olneyville Square provides visitors with the opportunity to find affordable bicycles & bike parts along with the help and training to get their bikes on the road. If you’re looking for used parts, a bike-project to wrench on, a bike to ride, to donate your old bike/parts or to take a class on bicycle mechanics – you’ve come to the right place. **Note: all programs suspended indefinitely due to COVID-19.**</p>

<h2>Our Mission</h2>
<p>Educating, empowering, and building community by connecting people and bicycles.</p>

<iframe src="https://player.vimeo.com/video/495848749" width="640" height="360" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
<p><a href="https://vimeo.com/495848749">Recycle-a-Bike Providence</a> from <a href="https://vimeo.com/user130239366">Recycle-a-Bike (PVD)</a> on <a href="https://vimeo.com">Vimeo</a>.</p>

<h2>Our Vision</h2>
<p>Valuable connections are made in our community shop among bicycle riders. By learning and sharing bike maintenance knowledge, people learn to believe in themselves and their community. Our programs make the simple technology of these pedal powered machines available to all with the help of the volunteer staff and general skill sharing.</p>

<p>Mobility on a bicycle is an expression of our freedom and equality! We encourage members of the public to participate in cycling as part of a healthy and active lifestyle – not just as a recreational activity, but also as a viable mode of transportation.</p>

Ride safely on the road. Be predictable, aware, courteous, and confident. Keep riding: you are a legal vehicle with the same rights on the road! Download cycling safety tips from the <a href="http://www.nbwclub.org/resources/DMVbrochure-2009.pdf">Narragansett Bay Wheelmen</a> and learn more about <a href="http://www.dot.ri.gov/travel/bikeri/">riding during COVID-19</a> (via RIDOT’s Bike RI page).</p>

<h2>Board of Directors</h2>
<ul>
<li>John Olivo, President</li>
<li>Sandra Victorino, Vice-President</li>
<li>Robert Serinsky, Treasurer</li>
<li>Jack Hartman, Secretary</li>
<li>Thomas Bacon</li>
<li>Cachi Carvalho</li>
<li>Chris Gambardella</li>
<li>Daniela Monge</li>
<li>Ed Raff</li>
<li>Kurt Teichert</li>
</ul>

**Comment by mrengy** [comment]
Whoops, didn’t realize that was Chelsea! And nice new photo choice. ;)

**Comment by jas14** [comment]
Done!
