### ISSUE TITLE
Blog Page Content

### ISSUE THREAD

**Issue by hartman313** [mrengy/recycleabike#128]
https://www.devsite.recycleabike.org/blog/

1. Add a header image - suggesting IMG_0070.jpg from the provided assets.

2. We'll need to migrate the latest blog articles. We can re-run the script you first used or manually update as there has only been 1 new article since the BLM article.

3.  The feed seems to be surfacing articles from 2018? See Summer Bike sale example: https://www.devsite.recycleabike.org/2018/06/07/summer-bike-sale-3/. Can we only display articles from 2019 -> Present?

Some unpublished posts ^ need to be removed.

**Comment by jas14** [comment]
Just put all posts before 2019 in draft mode so they won't appear on the site.

**Comment by jas14** [comment]
Still fucked, doesn't respect max-width container, no idea how to repro locally

**Comment by mrengy** [comment]
I'm not sure either - I think you saw the inline style that's being created that applies on the blog archive but doesn't show up on an interior page with the same div structure?

<img width="417" alt="Screen Shot 2021-01-20 at 9 39 52 PM" src="https://user-images.githubusercontent.com/2223603/105272808-14e1c980-5b68-11eb-85e7-123dfcc11b7c.png">

I restored this feature branch and overwrote that inline style with ca3db6bc3c3f7c7f69fe44e6e956997cf5d2e0be - a little gross, but good enough to get us to launch ;)

Also updated some of the div structure in d2c450decc253137399f1beb6a99854940a2f60d

There are still some horizontal alignment issues to fix, but stopping here for now.
