### ISSUE TITLE
Donate Page Content

### ISSUE THREAD

**Issue by hartman313** [mrengy/recycleabike#129]
https://www.devsite.recycleabike.org/donate/

___________________________________________________

<h2>Donate a Bike</h2>
<p>Can’t bear to see an unused bike collect dust in the basement or go to a landfill? Donate it to us for a second life! For the past 10 years, we have been refurbishing hundreds of old bikes for newly arrived refugees, students, city youth, and others through programs like Build-A-Bike, Wrenching Wednesdays, and Open Shop.</p>

<p>We accept all kinds of bicycles: cruisers, road, mountain, and BMX bikes. However if the bike has too much rust and appears beyond repair, please take it to a scrap yard. We accept donations of bicycles, bike tools, and bike parts during our open shop hours.</p>

<p>**In-person donations are currently suspended due to COVID-19. Please consider a making a monetary donation to help get us through this complicated time.**</p>

<h2>Donate Time</h2>
<p>Whatever your interest or availability, there is a place for you! Greeting visitors at Open Shop, distributing brochures, and fixing bikes are just a few examples of how you can help out. If you’d like to volunteer, start today by filling out this <a href="https://docs.google.com/forms/d/e/1FAIpQLSc0efW4QNxu8ljd9GFhzQozFvunjamsX_cT_Ye4b3Vc8YikCA/viewform">volunteer form</a> or emailing our <a href="mailto:shop@recycleabike.org">Shop Manager</a>. We can’t succeed without you!</p>

<h2>Donate Money</h2>
<p>Recycle-A-Bike is a 501(c)3 non-profit organization. Your gift is deductible to the full extent of the law.</p> 

<p>Where does the money go?</p>

<ul>
<li>$2000 is a 5-week Pedal Power safe cycling program for 20 kids</li>
<li>$1500 helps with one month of rent</li>
<li>$500 buys 45 free helmets for kids in our programs</li>
<li>$200 funds a fully refurbished bike for someone in need</li>
<li>$100 covers Build-a-Bike class tuition</li>
<li>$25 provides a U-lock for someone in need to keep their bike safe!
</ul>

**Comment by jas14** [comment]
Mostly done - the bottom of the page still has the donation button, which wasn't specified in the above issue (although I assume it should still be there?)
