### ISSUE TITLE
Partner Organizations Content

### ISSUE THREAD

**Issue by hartman313** [mrengy/recycleabike#130]
https://www.devsite.recycleabike.org/partner-organizations/

**Comment by hartman313** [comment]
Will follow up once I receive input from BOD. We're likely going to need a new layout, but don't want to commit to anything until we have a sense of the content.

**Comment by mrengy** [comment]
Also let's change the page title from "Partner Organizations" to "Partners" so that it fits nicer in the homepage grid per #132

**Comment by hartman313** [comment]
Alright @mrengy I heard back from the BOD. Let's change the nav item to "Friends" and remove Partners. This will also require an update to the URL alias.

We're going to keep this page really simple for the time being so we can ignore any notions of a grid or multiple sections that we had discussed previously. 
__________________________________



<h2>Valued Friends, Sponsors, and Resources</h2>

<ul>
<li><a href="https://bikenewportri.org/">Bike Newport</a></li>
<li><a href="https://bikesnotbombs.org/">Bikes Not Bombs</a></li>
<li><a href="http://www.blackstoneacademy.org/">Blackstone Academy</a></li>
<li>Blue Cross</li> 
<li><a href="https://www.providenceri.gov/">City of Providence</a></li>
<li><a href="http://www.cogentservices.org/">Cogent</a></li>
<li><a href="https://www.dashbicycle.com/">Dash Bicycle</a></li>
<li><a href="https://www.legendbicycle.com/">Legend Bicycle</a></li>
<li>The Lorber Family Foundation</li>
<li><a href="https://www.themethighschool.org/">The MET School</a></li>
<li><a href="http://www.nbwclub.org/">Narragansett Bay Wheelmen</a></li>
<li><a href="https://www.nbxbikes.com/">NBX</a></li>
<li><a href="https://www.providenceschools.org/">Providence City Schools</a></li>
<li><a href="https://www.providenceri.gov/parks-recreation/">Providence Parks Dept.</a></li>
<li><a href="https://ribike.org/">Rhode Island Bicycle Coalition</a></li>
<li><a href="https://wrwc.org/wp/what-we-do/red-shed-bike-programs/">WRWC/Red Shed</a></li>
<li><a href="https://www.uwri.org/">United Way</a></li>
</ul>

**Comment by hartman313** [comment]
This is complete.
