### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by hartman313** [mrengy/recycleabike#131]
Can we establish more definition between the footer and the homepage content? See design mockups in #132 

Move Contact Us sidebar to footer on all pages. Requires defining a new widget area of "footer"

(eliminate email list signup for now since we're not using it)

Also show "©2021 Recycle-A-Bike"

**Comment by mrengy** [comment]
Sounds good. Also would be nice if we could have the year update dynamically so it doesn't get out of date next year.

**Comment by jas14** [comment]
From https://github.com/mrengy/recycleabike/issues/132#issuecomment-752739429:

> Bump Contact Us and Newsletter sign-up to footer

**Comment by mrengy** [comment]
I fixed this locally, but for some reason, there are more registered widget areas appearing in wp-admin in the devsite than there are locally, and also when I put widgets into the devsite's new footer widget area created by this update, they don't appear in the front end. Trying to get to the bottom of why there is different behavior locally versus on the devsite

**Comment by mrengy** [comment]
Got it sorted out on the devsite. Initially, I think there was a widget area ID conflict, which caused the new widget area to not appear and then appear and then widgets assigned were lost.
