### ISSUE TITLE
Homepage Navigation Grid

### ISSUE THREAD

**Issue by hartman313** [mrengy/recycleabike#132]
[Design mockups - source of truth](https://www.figma.com/file/3947HXs3UqNTmNxFFNXBmK/Recycle-a-Bike-Website?node-id=248198%3A448)

1. Keeping in line with the BOD's request for adding a minimal amount of visual flare, wondering if we can do a 2x2 grid of callouts for the 4 main sections of our site - About, Friends (replaces Partner Organizations page), Blog, Donate ? Each photo could be 375x375 with a supporting h3 or an overlap like the masthead. On mobile callouts would stack in a single column. This grid would fall below the Our Programs section. Initially, the grid could be hardcoded. See #133 as a next step.

4. Blog feed would be removed altogether from the homepage

3. Remove Contact Us and Newsletter sign-up from the sidebar. #131 brings them into the footer instead

4. On tablet / desktop layouts, put "our programs" content into sidebar

**Comment by hartman313** [comment]
1. Is it possible to install a lightweight JS slider that can churn through 2-3 photos? Not providing an abundance of value (sliders rarely do) outside of visual flare, but I know the BOD would be appreciative

2. Keeping in line with the BOD's request for adding a minimal amount of visual flare, wondering if we can do a 2x2 grid of callouts for the 4 main sections of our site - About, Partners, Blog, Donate ? Each photo could be 375x375 with a supporting h3 or an overlap like the masthead. On mobile callouts would stack in a single column. This grid would fall below the Our Programs section. Blog feed would be removed altogether from the homepage

3. Bump Contact Us and Newsletter sign-up to footer

**Comment by mrengy** [comment]
Nice-to-have: create this as a Menu in WordPress

**Comment by mrengy** [comment]
Related to #131

**Comment by mrengy** [comment]
I'll take a pass at mocking this up and making sure we're on the same page before we write any code.

**Comment by mrengy** [comment]
A couple of examples of email signup lists in the footer:

https://bloggingwizard.com/email-sign-up-form-examples/

https://optinmonster.com/14-high-converting-places-to-add-email-signup-forms-to-build-your-list/#10_Footer

**Comment by mrengy** [comment]
<img width="360" alt="Home (mobile)" src="https://user-images.githubusercontent.com/2223603/103445291-21959080-4c40-11eb-88e2-b636135764db.png">
Here's a first pass at a mobile layout - thoughts? Haven't mocked up tablet and desktop sizes yet

**Comment by hartman313** [comment]
I think this looks nice. Wondering if given the way in looks in mobile if we remove the overlay from the header and just put the block of text beneath. Like to show more of that masthead if possible.

**Comment by mrengy** [comment]
Thanks. I’ll work on the other size layouts. Yeah, I think that’s a good idea to move the text block below the header image on mobile screen size. 

--

**Comment by mrengy** [comment]
Here's an [updated design](https://www.figma.com/file/3947HXs3UqNTmNxFFNXBmK/Recycle-a-Bike-Website?node-id=248198%3A448) for all the browser size layouts. I'll also edit the original comment with all the takeaways for clarity.

**Comment by mrengy** [comment]
I'm splitting out some of these points into other issues, to make it a bit more manageable

**Comment by mrengy** [comment]
Got a first pass at this. Some spacing and grid item height is still a little funny on tablet / desktop layouts

**Comment by mrengy** [comment]
Desktop layout: expand grid across whole width, move "about us" above grid
