### ISSUE TITLE
Write initial content in WordPress for single page temporary site

### ISSUE THREAD

**Issue by mrengy** [mrengy/recycleabike#35]
Will want to unpublish any pages we don't want to show up in search results

**Comment by mrengy** [comment]
Will want to unpublish any pages we don't want to show up in search results

**Comment by jas14** [comment]
Content [is up](https://www.devsite.recycleabike.org/), all pages except Donate are set to Private status, and I removed navigation from the header.

**Comment by jas14** [comment]
And removed the "Recent Posts" and "Archives" widgets to conform to the Figma.
