### ISSUE TITLE
Fix container ending too early

### ISSUE THREAD

**Issue by jas14** [mrengy/recycleabike#41]
<img width="1400" alt="Screen Shot 2020-10-01 at 4 36 39 PM" src="https://user-images.githubusercontent.com/569991/94866514-1f375680-0405-11eb-8255-9fd085013da0.png">

Note the gutters don't extend down to the footer. 😞

**Comment by mrengy** [comment]
Nice work!

Oh, yeah. That’s one thing that I remember being a little tricky in this theme. I would have to look into it, but I have a vague memory of how to address it. 

-- 
Mike Eng
401-234-4611
www.mike-eng.com
www.linkedin.com/in/mikeeng401

**Comment by mrengy** [comment]
This is weird. Wasn't what I thought it was. I wasn't able to reproduce it in Mac OS 10.14.6 in Chrome, Firefox, Brave, or Safari. Also, looks as though the logo is shifted up off the page. Are you still seeing this? If so, what browser version and OS? I also wonder if there's something else going on like a plugin doing strange things.

**Comment by mrengy** [comment]
Or maybe it only appears at a certain window size (which exceeds the size of my built-in monitor)?

**Comment by jas14** [comment]
Alas, it's still there. My window was just too vertically short.
