### ISSUE TITLE
Make caption content editable in WordPress 

### ISSUE THREAD

**Issue by mrengy** [mrengy/recycleabike#48]
This part:

<p>Recycle-a-Bike is a non-profit community bike shop in Providence, RI.</p>
				<p>Our mission is educating, empowering, and building community by connecting people and bicycles.</p>

Should be editable in WordPress. Perhaps as a custom field on the homepage?

**Comment by jas14** [comment]
https://wordpress.org/support/article/custom-fields/

**Comment by mrengy** [comment]
I added the custom field on the page. Need to display it in the theme next.

**Comment by mrengy** [comment]
There were literally about 30 other junk custom fields leftover from the Arvada theme :/ I deleted them. 

--
