### ISSUE TITLE
Style single page template

### ISSUE THREAD

**Issue by mrengy** [mrengy/recycleabike#75]

**Comment by jas14** [comment]
I'll work with one of the pages in draft/private mode to style 👍 
note to self;
- image header like front page
- white background like front page

**Comment by mrengy** [comment]
Thanks!

I actually published a couple - https://www.devsite.recycleabike.org/partner-organizations/ and https://www.devsite.recycleabike.org/about-us/

So you can work with those

**Comment by mrengy** [comment]
Hi! Don't mean to step on your toes with this, but I did some work on it since it is sort of a precursor for a bunch of other work

**Comment by mrengy** [comment]
I think this is mostly done. Closing for now. We can open another issue for adjustments if needed
